### ISSUE TITLE
show current/last cursor position

### ISSUE THREAD

**Issue by cquest** [Zigazou/miedit#2]
It would simplify a lot editing is the current/last cursor position was visible.
Blinking cursor could be a simple way to do it ?

**Comment by Zigazou** [comment]
I still need to implement the Minitel blinking cursor (which is disabled by default) therefore a blinking cursor would be ambiguous.It could be a frame (an empty rectangle) ?

**Comment by cquest** [comment]
You're right, an empty rectangle is a better option not to mix with the cursor, but when editing the cursor does not mean much exept during "play"

**Comment by Zigazou** [comment]
The functionality has been added to the summerrefactor branch ! (at last ;-) )

**Comment by Zigazou** [comment]
This is now merged in the master branch.

**Comment by Zigazou** [comment]
This is now merged in the master branch.
