### ISSUE TITLE
Export doesn't work when there are Graphics

### ISSUE THREAD

**Issue by t0mg** [Zigazou/miedit#4]
Il semblerait que la fonction d'import/export est cassée quand la page contient un objet Graphics.

Cas minimal: à partir d'une page vide, ajouter juste 1 objet Graphics dans le tree et colorer 1 pixel dedans. La fonction Export génère alors un JSON cassé (vers la fin des bytes du thumbnail) et donc impossible à importer.

**Comment by Zigazou** [comment]
L’export fonctionne correctement désormais :-)
