### ISSUE TITLE
Glitch Safari - Minitel-loader

### ISSUE THREAD

**Issue by XReyRobert** [Zigazou/miedit#5]
Un redimensionnement de la fenêtre du navigateur (ou changement de tab) est nécéssaire pour que 
la page s'affiche correctement sur Safari Mac...

**Comment by XReyRobert** [comment]
Bonjour,
Une copie d'écran n'aiderait pas bcp. En fait la page reste totalement vierge jusqu'au moment on soit on resize la fenêtre, soit elle perd le focus. A ce moment là, la page vidéotex apparait en cours de rendering. (Elle était donc bien en train de dérouler dés le départ)

Il y a effectivement une erreur, localisée dans skitch.sh..  "type error"

![screen shot 2018-04-15 at 02 05 28](https://user-images.githubusercontent.com/38261891/38773623-82359762-4051-11e8-8205-07087faf840c.png)

**Comment by Zigazou** [comment]
Je n’ai pas trouvé grand chose à propos de ce genre de bug sur Internet :-/

Étant donné le message d’erreur et sa provenance, peut-être qu’un plugin installé dans Safari réagit mal au contenu de miedit.

Peux-tu regarder dans les extensions installées sur Safari et en désactiver un maximum pour voir si le comportement se reproduit ?

**Comment by XReyRobert** [comment]
Je doute que ce soit une extension car safari sur iPad se comporte de la même façon... par contre pas de resize possible mais la page apparaît lorsqu’on change l’orientation de la tablette....

**Comment by Zigazou** [comment]
J’ai ajouté une balise viewport aux fichiers html, peux-tu vérifier si le comportement se produit toujours ou s’il y a du nouveau ?

**Comment by XReyRobert** [comment]
On dirait bien que ca marche! testé en local.

**Comment by Zigazou** [comment]
Super !
